'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { Heart, Image as ImageIcon, ShoppingCart, Trash2 } from 'lucide-react';
import { createClient } from '@/utils/supabase';
import { formatNaira } from '@/utils/money';
import { useCart } from '@/context/CartContext';

type SavedProduct = { id: string; title: string; price: number; seller_id: string; description?: string | null; image_url?: string | null; stock?: number | null };
type SavedItem = { id: string; products: SavedProduct | null };

export default function WishlistPage() {
  const supabase = createClient(); const { addToCart, getQuantity } = useCart();
  const [items, setItems] = useState<SavedItem[]>([]); const [loading, setLoading] = useState(true);
  useEffect(() => { void (async () => { const { data: { user } } = await supabase.auth.getUser(); if (!user) { setLoading(false); return; } const { data } = await supabase.from('wishlists').select('id, products ( id, title, price, seller_id, description, image_url, stock )').eq('user_id', user.id); setItems((data || []) as unknown as SavedItem[]); setLoading(false); })(); }, [supabase]);
  const remove = async (id: string) => { const { error } = await supabase.from('wishlists').delete().eq('id', id); if (!error) setItems(current => current.filter(item => item.id !== id)); };
  return <div className="buyer-secondary mx-auto max-w-3xl space-y-4 py-2"><Link href="/buyer" className="inline-flex items-center gap-2 text-xs font-bold text-[#81756d] hover:text-[#d8552e]">← Back to home</Link><header className="rounded-[1.75rem] bg-gradient-to-br from-[#ff9a55] to-[#e85f35] p-6 text-white"><Heart size={22} fill="currentColor" className="text-white/90" /><h1 className="mt-3 text-2xl font-black">Saved items</h1><p className="mt-1 text-sm text-white/80">Keep your favourites here until you are ready.</p></header>{loading ? <div className="grid grid-cols-2 gap-3 animate-pulse sm:grid-cols-3">{[1,2,3,4,5,6].map(item => <div key={item}><div className="aspect-[.9] rounded-[1.35rem] bg-[#eee4dc]" /><div className="mt-3 h-3 w-3/4 rounded bg-[#eee4dc]" /><div className="mt-2 h-3 w-1/2 rounded bg-[#f4eee9]" /></div>)}</div> : items.length === 0 ? <div className="rounded-[1.5rem] bg-white p-10 text-center shadow-sm"><Heart className="mx-auto text-[#ef6b3b]" size={34} /><h2 className="mt-3 font-bold text-[#251d18]">Nothing saved yet</h2><p className="mt-1 text-sm text-[#81756d]">Tap the heart on any product to save it for later.</p><Link href="/buyer" className="mt-5 inline-block rounded-full bg-[#2e2520] px-5 py-3 text-sm font-bold text-white">Explore market</Link></div> : <div className="grid grid-cols-2 gap-x-3 gap-y-6 sm:grid-cols-3">{items.map(item => { const product = item.products; if (!product) return null; return <article key={item.id}><div className="relative aspect-[.9] overflow-hidden rounded-[1.35rem] bg-[#f3eee8]">{product.image_url ? <img src={product.image_url} alt={product.title} className="h-full w-full object-cover" /> : <ImageIcon className="absolute inset-0 m-auto text-[#c9bfb2]" />}<button onClick={() => remove(item.id)} className="absolute right-2 top-2 grid h-8 w-8 place-items-center rounded-full bg-white/90 text-[#d8552e]" aria-label={`Remove ${product.title} from saved`}><Trash2 size={15}/></button></div><h2 className="mt-2 line-clamp-1 text-sm font-bold text-[#251d18]">{product.title}</h2><p className="mt-0.5 text-sm font-black text-[#ef6b3b]">₦{formatNaira(product.price)}</p>{getQuantity(product.id) > 0 ? <Link href="/buyer/cart" className="mt-2 flex items-center gap-1.5 rounded-full bg-[#e8f7ef] px-3 py-2 text-[11px] font-bold text-[#17805b]"><ShoppingCart size={14} fill="currentColor" /> Added</Link> : <button onClick={() => addToCart(product)} className="mt-2 flex items-center gap-1.5 rounded-full bg-[#fff0e9] px-3 py-2 text-[11px] font-bold text-[#c9552e]"><ShoppingCart size={14}/> Add to cart</button>}</article>; })}</div>}</div>;
}
