/**
 * Seller identity-verification uploads (student ID image + short video).
 *
 * Files land in the PRIVATE `verification-documents` bucket, namespaced under
 * `{userId}/` so Storage RLS scopes access to the owner (and to admins via the
 * service-role client). Because the bucket is private there are no public URLs;
 * the stored value is the object *path*, and administrators view the file with
 * a signed URL generated by the admin API route.
 *
 * Enforces per-file type and size:
 *   - ID image: JPG/PNG/WEBP up to 1MB (users compress before upload).
 *   - Video:    MP4/WEBM/MOV up to 2MB (short in-app recording, keeps storage small).
 * The "about 3 seconds" requirement is validated in the UI by reading the
 * `<video>` metadata length before upload (this util only guards size/type).
 */
const MAX_IMAGE_BYTES = 1 * 1024 * 1024; // 1MB
const MAX_VIDEO_BYTES = 2 * 1024 * 1024; // 2MB
const ALLOWED_IMAGE = ['image/jpeg', 'image/png', 'image/webp'];
const ALLOWED_VIDEO = ['video/mp4', 'video/webm', 'video/quicktime'];
const BUCKET = 'verification-documents';

import type { SupabaseClient } from '@supabase/supabase-js';

type StorageClient = Pick<SupabaseClient, 'storage'>;

type UploadResult = { ok: true; path: string } | { ok: false; error: string };

function extFor(file: File): string {
  return file.name.split('.').pop()?.toLowerCase() || 'bin';
}

/** `video/webm;codecs=opus` → `video/webm`. Blob types often carry parameters. */
function baseType(file: File): string {
  return (file.type || '').split(';')[0].trim().toLowerCase();
}

/** Upload the student ID card image. Returns the object path, not a public URL. */
export async function uploadStudentId(
  supabase: StorageClient,
  userId: string,
  file: File | null,
): Promise<UploadResult> {
  if (!file) return { ok: true, path: '' };
  if (!ALLOWED_IMAGE.includes(baseType(file))) {
    return { ok: false, error: 'Only JPG, PNG or WEBP images are allowed for your ID card.' };
  }
  if (file.size > MAX_IMAGE_BYTES) {
    return { ok: false, error: 'ID card image must be 1MB or smaller. Please compress it.' };
  }
  const path = `${userId}/student-id_${Date.now()}.${extFor(file)}`;
  const { data, error } = await supabase.storage.from(BUCKET).upload(path, file, {
    upsert: true,
  });
  if (error || !data?.path) {
    console.error('[verify] id upload failed', error);
    return { ok: false, error: 'Could not upload your ID card. Please try again.' };
  }
  return { ok: true, path: data.path };
}

/** Upload the 3-second verification selfie video. Returns the object path. */
export async function uploadVerificationVideo(
  supabase: StorageClient,
  userId: string,
  file: File | null,
): Promise<UploadResult> {
  if (!file) return { ok: true, path: '' };
  if (!ALLOWED_VIDEO.includes(baseType(file))) {
    return { ok: false, error: 'Only MP4, WEBM or MOV videos are allowed.' };
  }
  if (file.size > MAX_VIDEO_BYTES) {
    return { ok: false, error: 'Verification video must be 2MB or smaller. Keep it short and low-resolution.' };
  }
  const path = `${userId}/verification-video_${Date.now()}.${extFor(file)}`;
  const { data, error } = await supabase.storage.from(BUCKET).upload(path, file, {
    upsert: true,
  });
  if (error || !data?.path) {
    console.error('[verify] video upload failed', error);
    return { ok: false, error: 'Could not upload your verification video. Please try again.' };
  }
  return { ok: true, path: data.path };
}